name: CI
on: [push, pull_request]
jobs:
    tests:
        runs-on: ubuntu-latest

        steps:
            - name: Code checkout
              uses: actions/checkout@v4

            - name: PHP setup
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.3"
                  extensions: mbstring, intl
                  coverage: none

            - name: Install Composer
              run: composer install

            - name: Run tests
              run: php bin/phpunit
