name: CI
on: [push, pull_request]
jobs:
    tests:
        runs-on: ubuntu-latest

        steps:
            - name: Code checkout
              uses: actions/checkout@v4

            - name: PHP setup
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.3"
                  extensions: mbstring, intl
                  coverage: none

            - name: Install Composer
              run: composer install

            - name: Run tests
              run: php bin/phpunit

    deploy:
        runs-on: ubuntu-latest
        needs: tests
        if: ${{ success() }}
    
        steps:
          - name: Code checkout
            uses: actions/checkout@v4
    
          - name: Deploy on FTP
            uses: SamKirkland/FTP-Deploy-Action@v4.3.6
            with:
              server: ${{ secrets.HOST }}
              username: ${{ secrets.ID }}
              password: ${{ secrets.PASSWORD }}
              exclude: |
                **/.git/**
                **/.git*
                **/.github/**
                **/node_modules/**
                **/tests/**
                var/**
                **/.DS_Store
                **/Thumbs.db
              state-name: .ftp-deploy-sync-state.json
              log-level: verbose
              dangerous-clean-slate: true